import Navbar from '@/components/navbar';
import type { Metadata } from 'next';
import { Chiron_GoRound_TC, Inter, Song_Myung } from 'next/font/google';
import Image from 'next/image';
import './globals.css';
import Footer from '@/components/footer';

const interSans = Inter({
  variable: '--font-inter-sans',
  subsets: ['latin'],
});

const songMyeongjo = Song_Myung({
  variable: '--font-song-serif',
  weight: '400',
});

const chironSans = Chiron_GoRound_TC({
  variable: '--font-chiron-sans',
  weight: '400',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: LayoutProps<'/'>) {
  return (
    <html
      lang='en'
      className={`${interSans.variable} ${songMyeongjo.variable} ${chironSans.variable} h-full antialiased`}
    >
      <body className='min-h-full relative flex flex-col'>
        <div className='w-full absolute inset-x-0 top-0 pointer-events-none'>
          <Image
            src={'/assets/White_Cloud.svg'}
            alt='white cloud'
            width={1566}
            height={308}
            className='w-full h-auto absolute top-12 z-1'
          />
          <Image
            src={'/assets/Blue_Cloud.svg'}
            alt='blue cloud'
            width={894}
            height={262}
            className='absolute w-1/2 md:w-auto top-12 right-1/6'
          />
          <Image
            src={'/assets/Emblem.svg'}
            alt='emblem'
            width={168}
            height={168}
            className='absolute size-20 md:size-36 left-6 md:left-12 top-0'
          />
          <div className='w-full h-24 md:h-40 flex-1 bg-linear-to-b from-[#A8CCF3] to-[#D0E4F9]' />
        </div>
        <header className='w-full px-6 lg:px-36 z-2 mt-24 lg:mt-48'>
          <div className='flex flex-col gap-2 lg:gap-2 lg:flex-row justify-between items-center lg:items-end'>
            <div className='flex flex-col'>
              <h1 className='font-song text-5xl'>유메의 블로그</h1>
              <span className='text-sm text-slate-400'>
                여기는 유메의 블로그가 될 공사현장입니다
              </span>
            </div>
            <Navbar />
          </div>
          <hr className='mt-4 border-slate-400' />
        </header>
        <main className='flex-1 flex flex-col px-6 lg:px-36 bg-white z-2'>
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
